### ISSUE TITLE
New Curve Deployment Checklist

### ISSUE THREAD

**Issue by chanharryhk** [dfx-finance/protocol#10]
There are couple of steps when deploying a new pool w/ staking contracts
In general it goes assimilator -> verification on etherscan -> pool deployment

1. Creating and deploying new non USD stablecoin assimilators
    Note: The deployment of new assimilators is to obtain the price feeds from new non USD stablecoins from chainlink
    - [ ] Copy and paste an existing assimilator contract from [here](https://github.com/dfx-finance/protocol/tree/main/contracts/assimilators). It will make your life easier if you copied from an assimilator that shared the same decimal offsets 
    i.e. CADC is 18, XSGD/TRYB/USDC/NZDS is 6, EURS is 2
    ![Screen Shot 2022-01-10 at 12 19 27 PM](https://user-images.githubusercontent.com/25423613/148851097-e9b1c22f-3fd0-4b8a-991d-c70fbb835c5c.png)
    - [ ] Change copied stablecoin names to new stablecoin i.e. xidr → jpyc
    Note: be careful about using a single find and replace because there are different capitalizations of the stablecoin abbreviation 
    i.e. xidr vs XIDR
    - [ ] Change chainlink oracle to respective price feed [here](https://docs.chain.link/docs/ethereum-addresses/)
    Note: It is important to be using the right chain for the right feed 
    i.e. CAD polygon vs CAD mainnet
    ```
    IOracle private constant oracle = IOracle(0x91b99C9b75aF469a71eE1AB528e8da994A5D7030);
    ```
    - [ ] Change token address to respective erc20 token
    ```
    IERC20 private constant xidr = IERC20(0xebF2096E01455108bAdCbAF86cE30b6e5A72aa52);
    ```
2. Testing assimilators
    Once you have the assimilators written you'll need to test them
    - [ ] Add the addresses to Constants.ts, create a mint function on Utils.ts (mainnet branch should work out of the box with FiatTokenV2 (USDC fork), and polygon branch should work out of the box with mapped tokens), and finally add the newly created mint function to Setup.ts
    - [ ] Add the addresses to Constants.ts, create a mint function on Utils.ts (mainnet branch should work out of the box with FiatTokenV2 (USDC fork), and polygon branch should work out of the box with mapped tokens), and finally add the newly created mint function to Setup.ts
3. Assimilator Deployment
    Note: Assimilator deployment can be done from any address
    - [ ] Create your own .env file inside the protocol repo
    Note: it would be best practice to be using a dev private key just incase
    ```
    REMOTE_URL=http://127.0.0.1:8545
    RPC_URL=http://127.0.0.1:8545
    PRIVATE_KEY=0000000000000000000000000000000000000000000000000000000000000001
    ```
    - [ ]  double check that this file is in the gitignore because the information is sensitive
    - [ ]  look into [here](https://github.com/dfx-finance/protocol/blob/main/scripts/07-deploy-xidr-assimilators.ts) for an example of contract deployments scripts
    - [ ]  simply run this in your terminal to deploy the assimilator
    ```
    yarn hh:run scripts/07-deploy-xidr-assimilators.ts --network remote
    ```
    - [ ]  ensure that the deployment json of the assimilator is recorded and pushed to github
4. Verification on Etherscan
    - [ ]  install multisol [here](https://github.com/paulrberg/multisol)
    - [ ]  generate multisol files
    ```multisol contracts/assimilators/xxxx ToUsdAssimilator.sol```
    - [ ] Select the correct options
    - [ ] Select the options for “Solidity (Multi-Part files)”
    - [ ] Select the correct compiler version for assimilators “v0.7.3”
    - [ ] Select the correct license “MIT License (MIT)”
    - [ ] Accept the terms of service and click continue
    <img width="718" alt="Screen Shot 2022-01-10 at 4 52 03 PM" src="https://user-images.githubusercontent.com/25423613/148852094-dc356b79-e3b5-4d5e-b1da-39ec9a7d499b.png">
    
    - [ ] Make sure to click yes to the optimization
    <img width="162" alt="Screen Shot 2022-01-10 at 4 52 16 PM" src="https://user-images.githubusercontent.com/25423613/148852126-8382eeab-0178-4ced-9e13-d2f8cd5d46f8.png">
    
    - [ ] Select all the individual solidity files that to upload 
    <img width="765" alt="Screen Shot 2022-01-10 at 4 52 49 PM" src="https://user-images.githubusercontent.com/25423613/148852173-aa21514e-03e7-4cf1-8ba5-b039023fd871.png">
    
    - [ ]  click “i am not a robot” and then verify and publish
    - [ ]  delete the multisol folder from the protocol repository

5. Pool deployment through multisig
    - [ ]  Make a transaction to the [DFX factory](https://etherscan.io/address/0xd3C1bF5582b5f3029b15bE04a49C65d3226dFB0C) through the gnosis multisig through [here](https://gnosis-safe.io/app/eth:0x27E843260c71443b4CC8cB6bF226C3f77b9695AF)
    - [ ]  Gnosis multisig contract interactions
    1. newCurve - interacts with DFX factory
    - [ ]  Click “New Transaction” on the left
    - [ ]  Click “<> contract interaction”
    - [ ]  Paste the respective DFX factory address and the ABI should autofill
        i.e. 0xd3C1bF5582b5f3029b15bE04a49C65d3226dFB0C for mainnet
    - [ ]  Select “newCurve” and fill in the params properly and review the transaction
    - [ ]  Double check here because these values are important
Below is an example of the xidr newCurve deployment
    <img width="503" alt="Screen Shot 2022-01-10 at 5 12 48 PM" src="https://user-images.githubusercontent.com/25423613/148852596-a863de08-dc87-4b54-a60c-2d32c201cafa.png">
        
      2. setParams - interacts with deployed Pool
    - [ ]  Click “New Transaction” on the left
    - [ ]  Click “<> contract interaction”
    - [ ]  Paste the respective pool address that was just deployed and the ABI should autofill
        i.e. 0xdD39379AB7C93b9bAAE29E6eC03795d0bC99a889 for mainnet XIDR pool
    - [ ]  Select “setParams” and fill out the params properly and review the transaction
        Current recommended settings for the pool are 
    - [ ]  Double check here because these values are important
    <img width="518" alt="Screen Shot 2022-01-10 at 5 16 44 PM" src="https://user-images.githubusercontent.com/25423613/148852631-163719ce-56c4-432c-9fb5-775f028c7492.png">

        3. turnOffWhitelisting
    - [ ]  Click “New Transaction” on the left
    - [ ]  Click “<> contract interaction”
    - [ ]  Paste the respective pool address that was just deployed and the ABI should autofill
        i.e. 0xdD39379AB7C93b9bAAE29E6eC03795d0bC99a889 for mainnet XIDR pool
    - [ ]  Select “turnOffWhitelisting” and review the transactions

**Comment by adrianmcli** [comment]
Thanks @chanharryhk. Looks great, very detailed.

NTS, reference write-up from Kendrick here: https://github.com/dfx-finance/protocol/issues/7
